version: '3.9'

services:
    app:
        image: chat_application
        build:
            context: ./
            dockerfile: Dockerfile
        volumes:
            -   ./html-template/:/code/html-template:ro
        ports:
            -   8000:80
        restart: always
        depends_on:
            -   db
        environment:
            - WebSocketURL=${WebSocketURL}
            - DRIVER=${DRIVER}
            - DB_USER_NAME=${DB_USER_NAME}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_HOST=${DB_HOST}
            - DB_NAME=${DB_NAME}
        networks:
            - network
    db:
        hostname: ${DB_HOST}
        image: postgres:14.1-alpine
        restart: always
        environment:
            - POSTGRES_DB=${DB_NAME}
            - POSTGRES_USER=${DB_USER_NAME}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
        ports:
            - '5432:5432'
        volumes:
            - db:/var/lib/postgresql/data
        networks:
            - network

    nginx:
        image: nginx:alpine
        links:
            - app:app
        volumes:
            - ./ngnix/nginx.conf:/etc/nginx/conf.d/default.conf:ro
#            - ./ssl:/etc/nginx/ssl
        ports:
            - "880:80"
            - "8449:443"
        networks:
            - network



networks:
    network:
        name: chat_network

volumes:
  db:
    driver: local
    name: postgres